name: CI Pipeline
on: [push]
jobs: 
  build: 
    name: Build 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 5.0.x
    - run: cd Source cd RestAPI dotnet build